# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Mehran Taghian
tagline:          'Mehran Taghian'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
# description:      'Mehran is a Machine Learning Engineer'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mehran Taghian'
  # url:            https://twitter.com/mdo

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
